"""Core subpackage for pi_coding_agent — session management, bash execution, and system prompt."""

from pi_coding_agent.core.agent_session import (
    AgentSession,
    AgentSessionConfig,
    AgentSessionEvent,
    AgentSessionEventListener,
    AutoCompactionEndEvent,
    AutoCompactionStartEvent,
    AutoRetryEndEvent,
    AutoRetryStartEvent,
    PromptOptions,
    SessionStats,
)
from pi_coding_agent.core.bash_executor import (
    BashExecutorOptions,
    BashResult,
    execute_bash,
    execute_bash_with_operations,
)
from pi_coding_agent.core.event_bus import EventBus, create_event_bus
from pi_coding_agent.core.exec import ExecOptions, ExecResult, exec_command
from pi_coding_agent.core.messages import (
    BRANCH_SUMMARY_PREFIX,
    BRANCH_SUMMARY_SUFFIX,
    COMPACTION_SUMMARY_PREFIX,
    COMPACTION_SUMMARY_SUFFIX,
    BashExecutionMessage,
    BranchSummaryMessage,
    CompactionSummaryMessage,
    CustomMessage,
    bash_execution_to_text,
    convert_to_llm,
    create_branch_summary_message,
    create_compaction_summary_message,
    create_custom_message,
)
from pi_coding_agent.core.package_manager import (
    DefaultPackageManager,
    MissingSourceAction,
    PackageManager,
    PathMetadata,
    ProgressCallback,
    ProgressEvent,
    ResolvedPaths,
    ResolvedResource,
    create_package_manager,
)
from pi_coding_agent.core.session_manager import (
    CURRENT_SESSION_VERSION,
    BranchSummaryEntry,
    CompactionEntry,
    CustomEntry,
    CustomMessageEntry,
    FileEntry,
    LabelEntry,
    ModelChangeEntry,
    NewSessionOptions,
    SessionContext,
    SessionEntry,
    SessionHeader,
    SessionInfo,
    SessionInfoEntry,
    SessionManager,
    SessionMessageEntry,
    SessionTreeNode,
    ThinkingLevelChangeEntry,
    build_session_context,
    find_most_recent_session,
    get_latest_compaction_entry,
    load_entries_from_file,
    migrate_session_entries,
    parse_session_entries,
)
from pi_coding_agent.core.system_prompt import (
    BuildSystemPromptOptions,
    Skill,
    build_system_prompt,
)

__all__ = [
    # messages
    "BRANCH_SUMMARY_PREFIX",
    "BRANCH_SUMMARY_SUFFIX",
    "COMPACTION_SUMMARY_PREFIX",
    "COMPACTION_SUMMARY_SUFFIX",
    # session_manager
    "CURRENT_SESSION_VERSION",
    # agent_session
    "AgentSession",
    "AgentSessionConfig",
    "AgentSessionEvent",
    "AgentSessionEventListener",
    "AutoCompactionEndEvent",
    "AutoCompactionStartEvent",
    "AutoRetryEndEvent",
    "AutoRetryStartEvent",
    "BashExecutionMessage",
    # bash_executor
    "BashExecutorOptions",
    "BashResult",
    "BranchSummaryEntry",
    "BranchSummaryMessage",
    # system_prompt
    "BuildSystemPromptOptions",
    "CompactionEntry",
    "CompactionSummaryMessage",
    "CustomEntry",
    "CustomMessage",
    "CustomMessageEntry",
    # package_manager
    "DefaultPackageManager",
    # event_bus
    "EventBus",
    # exec
    "ExecOptions",
    "ExecResult",
    "FileEntry",
    "LabelEntry",
    "MissingSourceAction",
    "ModelChangeEntry",
    "NewSessionOptions",
    "PackageManager",
    "PathMetadata",
    "ProgressCallback",
    "ProgressEvent",
    "PromptOptions",
    "ResolvedPaths",
    "ResolvedResource",
    "SessionContext",
    "SessionEntry",
    "SessionHeader",
    "SessionInfo",
    "SessionInfoEntry",
    "SessionManager",
    "SessionMessageEntry",
    "SessionStats",
    "SessionTreeNode",
    "Skill",
    "ThinkingLevelChangeEntry",
    "bash_execution_to_text",
    "build_session_context",
    "build_system_prompt",
    "convert_to_llm",
    "create_branch_summary_message",
    "create_compaction_summary_message",
    "create_custom_message",
    "create_event_bus",
    "create_package_manager",
    "exec_command",
    "execute_bash",
    "execute_bash_with_operations",
    "find_most_recent_session",
    "get_latest_compaction_entry",
    "load_entries_from_file",
    "migrate_session_entries",
    "parse_session_entries",
]
