"""Unified multi-provider LLM API — Python port of @mariozechner/pi-ai."""

from pi_ai.api_registry import (
    ApiProvider,
    StreamFunction,
    StreamSimpleFunction,
    clear_api_providers,
    get_api_provider,
    get_api_providers,
    register_api_provider,
    unregister_api_providers,
)
from pi_ai.env_api_keys import get_env_api_key
from pi_ai.models import (
    calculate_cost,
    clear_model_registry,
    get_model,
    get_models,
    get_providers,
    models_are_equal,
    register_models,
    supports_xhigh,
)
from pi_ai.providers.amazon_bedrock import (
    BedrockOptions,
    stream_bedrock,
    stream_simple_bedrock,
)
from pi_ai.providers.anthropic import (
    AnthropicEffort,
    AnthropicOptions,
    stream_anthropic,
    stream_simple_anthropic,
)
from pi_ai.providers.azure_openai_responses import (
    AzureOpenAIResponsesOptions,
    stream_azure_openai_responses,
    stream_simple_azure_openai_responses,
)
from pi_ai.providers.github_copilot_headers import (
    build_copilot_dynamic_headers,
    has_copilot_vision_input,
    infer_copilot_initiator,
)
from pi_ai.providers.google import (
    GoogleOptions,
    GoogleThinkingLevel,
    stream_google,
    stream_simple_google,
)
from pi_ai.providers.google_gemini_cli import (
    GoogleGeminiCliOptions,
    build_request,
    extract_retry_delay,
    stream_google_gemini_cli,
    stream_simple_google_gemini_cli,
)
from pi_ai.providers.google_shared import (
    convert_tools as convert_google_tools,
)
from pi_ai.providers.google_shared import (
    is_thinking_part,
    map_stop_reason_string,
    map_tool_choice,
    requires_tool_call_id,
    retain_thought_signature,
)
from pi_ai.providers.google_shared import (
    map_stop_reason as map_google_stop_reason,
)
from pi_ai.providers.google_vertex import (
    GoogleVertexOptions,
    stream_google_vertex,
    stream_simple_google_vertex,
)
from pi_ai.providers.openai_codex_responses import (
    OpenAICodexResponsesOptions,
    stream_openai_codex_responses,
    stream_simple_openai_codex_responses,
)
from pi_ai.providers.openai_completions import (
    OpenAICompletionsOptions,
    convert_messages,
    stream_openai_completions,
    stream_simple_openai_completions,
)
from pi_ai.providers.openai_responses import (
    OpenAIResponsesOptions,
    stream_openai_responses,
    stream_simple_openai_responses,
)
from pi_ai.providers.openai_responses_shared import (
    ConvertResponsesMessagesOptions,
    ConvertResponsesToolsOptions,
    OpenAIResponsesStreamOptions,
    convert_responses_messages,
    convert_responses_tools,
    process_responses_stream,
)
from pi_ai.providers.register_builtins import (
    BUILT_IN_APIS,
    register_built_in_api_providers,
    reset_api_providers,
)
from pi_ai.providers.simple_options import (
    adjust_max_tokens_for_thinking,
    build_base_options,
    clamp_reasoning,
)
from pi_ai.providers.transform_messages import transform_messages
from pi_ai.stream import complete, complete_simple, stream, stream_simple
from pi_ai.types import (
    Api,
    AssistantContentBlock,
    AssistantMessage,
    AssistantMessageEvent,
    AssistantMessageEventStream,
    CacheRetention,
    CompatType,
    ContentBlock,
    Context,
    DoneEvent,
    ErrorEvent,
    ImageContent,
    KnownApi,
    KnownProvider,
    Message,
    Model,
    ModelCost,
    OpenAICompletionsCompat,
    OpenAIResponsesCompat,
    OpenRouterRouting,
    Provider,
    SimpleStreamOptions,
    StartEvent,
    StopReason,
    StreamOptions,
    TextContent,
    TextDeltaEvent,
    TextEndEvent,
    TextStartEvent,
    ThinkingBudgets,
    ThinkingContent,
    ThinkingDeltaEvent,
    ThinkingEndEvent,
    ThinkingLevel,
    ThinkingStartEvent,
    Tool,
    ToolCall,
    ToolCallDeltaEvent,
    ToolCallEndEvent,
    ToolCallStartEvent,
    ToolResultMessage,
    Transport,
    Usage,
    UsageCost,
    UserContentBlock,
    UserMessage,
    VercelGatewayRouting,
    deserialize_content_block,
    deserialize_message,
    deserialize_model,
    deserialize_usage,
    deserialize_usage_cost,
    serialize_content_block,
    serialize_message,
    serialize_model,
    serialize_usage,
    serialize_usage_cost,
)
from pi_ai.utils.json_parse import parse_streaming_json
from pi_ai.utils.overflow import get_overflow_patterns, is_context_overflow
from pi_ai.utils.sanitize_unicode import sanitize_surrogates
from pi_ai.utils.validation import validate_tool_arguments, validate_tool_call

__all__ = [
    "BUILT_IN_APIS",
    "AnthropicEffort",
    "AnthropicOptions",
    "Api",
    "ApiProvider",
    "AssistantContentBlock",
    "AssistantMessage",
    "AssistantMessageEvent",
    "AssistantMessageEventStream",
    "AzureOpenAIResponsesOptions",
    "BedrockOptions",
    "CacheRetention",
    "CompatType",
    "ContentBlock",
    "Context",
    "ConvertResponsesMessagesOptions",
    "ConvertResponsesToolsOptions",
    "DoneEvent",
    "ErrorEvent",
    "GoogleGeminiCliOptions",
    "GoogleOptions",
    "GoogleThinkingLevel",
    "GoogleVertexOptions",
    "ImageContent",
    "KnownApi",
    "KnownProvider",
    "Message",
    "Model",
    "ModelCost",
    "OpenAICodexResponsesOptions",
    "OpenAICompletionsCompat",
    "OpenAICompletionsOptions",
    "OpenAIResponsesCompat",
    "OpenAIResponsesOptions",
    "OpenAIResponsesStreamOptions",
    "OpenRouterRouting",
    "Provider",
    "SimpleStreamOptions",
    "StartEvent",
    "StopReason",
    "StreamFunction",
    "StreamOptions",
    "StreamSimpleFunction",
    "TextContent",
    "TextDeltaEvent",
    "TextEndEvent",
    "TextStartEvent",
    "ThinkingBudgets",
    "ThinkingContent",
    "ThinkingDeltaEvent",
    "ThinkingEndEvent",
    "ThinkingLevel",
    "ThinkingStartEvent",
    "Tool",
    "ToolCall",
    "ToolCallDeltaEvent",
    "ToolCallEndEvent",
    "ToolCallStartEvent",
    "ToolResultMessage",
    "Transport",
    "Usage",
    "UsageCost",
    "UserContentBlock",
    "UserMessage",
    "VercelGatewayRouting",
    "adjust_max_tokens_for_thinking",
    "build_base_options",
    "build_copilot_dynamic_headers",
    "build_request",
    "calculate_cost",
    "clamp_reasoning",
    "clear_api_providers",
    "clear_model_registry",
    "complete",
    "complete_simple",
    "convert_google_tools",
    "convert_messages",
    "convert_responses_messages",
    "convert_responses_tools",
    "deserialize_content_block",
    "deserialize_message",
    "deserialize_model",
    "deserialize_usage",
    "deserialize_usage_cost",
    "extract_retry_delay",
    "get_api_provider",
    "get_api_providers",
    "get_env_api_key",
    "get_model",
    "get_models",
    "get_overflow_patterns",
    "get_providers",
    "has_copilot_vision_input",
    "infer_copilot_initiator",
    "is_context_overflow",
    "is_thinking_part",
    "map_google_stop_reason",
    "map_stop_reason_string",
    "map_tool_choice",
    "models_are_equal",
    "parse_streaming_json",
    "process_responses_stream",
    "register_api_provider",
    "register_built_in_api_providers",
    "register_models",
    "requires_tool_call_id",
    "reset_api_providers",
    "retain_thought_signature",
    "sanitize_surrogates",
    "serialize_content_block",
    "serialize_message",
    "serialize_model",
    "serialize_usage",
    "serialize_usage_cost",
    "stream",
    "stream_anthropic",
    "stream_azure_openai_responses",
    "stream_bedrock",
    "stream_google",
    "stream_google_gemini_cli",
    "stream_google_vertex",
    "stream_openai_codex_responses",
    "stream_openai_completions",
    "stream_openai_responses",
    "stream_simple",
    "stream_simple_anthropic",
    "stream_simple_azure_openai_responses",
    "stream_simple_bedrock",
    "stream_simple_google",
    "stream_simple_google_gemini_cli",
    "stream_simple_google_vertex",
    "stream_simple_openai_codex_responses",
    "stream_simple_openai_completions",
    "stream_simple_openai_responses",
    "supports_xhigh",
    "transform_messages",
    "unregister_api_providers",
    "validate_tool_arguments",
    "validate_tool_call",
]
